M48
; DRILL file {KiCad 9.0.5} date 2026-06-11T00:17:33+0900
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-06-11T00:17:33+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X2.9945Y-3.6795
X2.9945Y-3.8705
T2
X2.8752Y-3.6677
X2.8752Y-3.8823
M30
